# Generated by Django 2.1 on 2018-08-20 10:39

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin', models.CharField(db_index=True, max_length=255, unique=True)),
                ('year', models.IntegerField()),
                ('make', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=255)),
                ('dimensions', models.CharField(max_length=255)),
                ('weight', models.CharField(max_length=255)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('data_owner', models.CharField(choices=[('decodethis', 'Decode this')], max_length=255)),
            ],
        ),
    ]
